### ISSUE TITLE
Crashes with "no signature found for built-in [...]"

### ISSUE THREAD

**Issue by bluewww** [mooz/xkeysnail#10]
I run
```
xkeysnail config.py
``` 
where config.py is the one from the examples folder. I'm added to the input and uinput group, so that I don't need to run it as root.

It crashes, printing the following stacktrace:
```
[...] (omitted)

Okay, now enable remapping on the following device(s):

-------------------------------------------------------------------------------------
Device               Name                                Phys
-------------------------------------------------------------------------------------
/dev/input/event3    Logitech USB Keyboard               usb-0000:00:14.0-2/input0
/dev/input/event5    Corsair Corsair K70R Gaming Keyboard usb-0000:00:1a.0-1.5/input0
/dev/input/event8    Corsair Corsair K70R Gaming Keyboard usb-0000:00:1a.0-1.5/input2

Traceback (most recent call last):
  File "/usr/bin/xkeysnail", line 6, in <module>
    cli_main()
  File "/usr/lib/python3.4/site-packages/xkeysnail/__init__.py", line 48, in cli_main
    loop(select_device(args.devices))
  File "/usr/lib/python3.4/site-packages/xkeysnail/input.py", line 89, in loop
    on_event(event, device.name)
  File "/usr/lib/python3.4/site-packages/xkeysnail/transform.py", line 261, in on_event
    if len(signature(condition).parameters) == 2:
  File "/usr/lib64/python3.4/inspect.py", line 2063, in signature
    return _signature_internal(obj)
  File "/usr/lib64/python3.4/inspect.py", line 1965, in _signature_internal
    skip_bound_arg=skip_bound_arg)
  File "/usr/lib64/python3.4/inspect.py", line 1890, in _signature_from_builtin
    raise ValueError("no signature found for builtin {!r}".format(func))
ValueError: no signature found for builtin <built-in method search of _sre.SRE_Pattern object at 0x7fb303281e00>

```
Please tell me if I need to provide additional debugging information.

Edit:
Seems to be a python 3.4 problem. Works flawlessly with python 3.6

**Comment by joshgoebel** [comment]
Might help to first reduce it down to the SMALLEST config file that could trigger the bug... so we knew what to look at...

**Comment by joshgoebel** [comment]
> Works flawlessly with python 3.6

Awesome, just saw this.  Can we close this issue then?  I think Python 3.4 may just to too fat back to properly support (8 years ago now).

**Comment by bluewww** [comment]
Yep I'm closing this
