### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by gk2803** [mooz/xkeysnail#125]
**OS: Ubuntu 20.10**
**python version: 3.8**

tried installng both from source code and pip but get this error when running `sudo xkeysnail config.py`
```


Traceback (most recent call last):
  File "/usr/local/bin/xkeysnail", line 6, in <module>
    cli_main()
  File "/usr/local/lib/python3.8/dist-packages/xkeysnail/__init__.py", line 62, in cli_main
    eval_file(args.config)
  File "/usr/local/lib/python3.8/dist-packages/xkeysnail/__init__.py", line 5, in eval_file
    with open(path, "rb") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.py'
Exception ignored in: <function InputDevice.__del__ at 0x7fe8685e1310>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/evdev/device.py", line 160, in __del__
  File "/usr/local/lib/python3.8/dist-packages/evdev/device.py", line 305, in close
  File "/usr/local/lib/python3.8/dist-packages/evdev/eventio_async.py", line 55, in close
  File "/usr/lib/python3.8/asyncio/events.py", line 722, in get_event_loop_policy
  File "/usr/lib/python3.8/asyncio/events.py", line 715, in _init_event_loop_policy
ImportError: sys.meta_path is None, Python is likely shutting down

```

**Comment by luizoti** [comment]
First, check if your config.py file exist ---> `No such file or directory: 'config.py'`

I suppose the error: `ImportError: sys.meta_path is None, Python is likely shutting down`, happens as a result of the error: `FileNotFoundError: [Errno 2] No such file or directory: 'config.py'`.

I believe that error `ImportError: sys.meta_path is None, Python is likely shutting down` should happen in certain situations, where the other error occurs during execution.

**Comment by luizoti** [comment]
I submit this PR: [154](https://github.com/gvalkov/python-evdev/pull/154) to evdev repo, probably will fix the `ImportError: sys.meta_path is None, Python is likely shutting down`.

But your problem is missing config.py.

**Comment by CSpencerND** [comment]
I'm getting the same errors even though I have my config file
```
Traceback (most recent call last):
  File "/usr/local/bin/xkeysnail", line 6, in <module>
    cli_main()
  File "/usr/local/lib/python3.9/dist-packages/xkeysnail/__init__.py", line 62, in cli_main
    eval_file(args.config)
  File "/usr/local/lib/python3.9/dist-packages/xkeysnail/__init__.py", line 6, in eval_file
    exec(compile(file.read(), path, 'exec'), globals())
  File "/home/cs/.config/xkeysnail/config.py", line 2, in <module>
    from xkeysnail.transform import *
  File "/usr/local/lib/python3.9/dist-packages/xkeysnail/transform.py", line 16, in <module>
    def get_active_window_wm_class(display=Xlib.display.Display()):
  File "/usr/lib/python3/dist-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python3/dist-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/lib/python3/dist-packages/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":1": b'No protocol specified\n'
Exception ignored in: <function InputDevice.__del__ at 0x7f8a2b5b7940>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 160, in __del__
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 305, in close
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 55, in close
  File "/usr/lib/python3.9/asyncio/events.py", line 725, in get_event_loop_policy
  File "/usr/lib/python3.9/asyncio/events.py", line 718, in _init_event_loop_policy
ImportError: sys.meta_path is None, Python is likely shutting down
```

**Comment by luizoti** [comment]
In your case the real error is:

`Xlib.error.DisplayConnectionError: Can't connect to display ":1": b'No protocol specified\n'`

In general, any error raised by Xkeysnail will return similar errors, like this:

```Exception ignored in: <function InputDevice.__del__ at 0x7f8a2b5b7940>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 160, in __del__
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 305, in close
  File "/usr/lib/python3/dist-packages/evdev/eventio_async.py", line 55, in close
  File "/usr/lib/python3.9/asyncio/events.py", line 725, in get_event_loop_policy
  File "/usr/lib/python3.9/asyncio/events.py", line 718, in _init_event_loop_policy
ImportError: sys.meta_path is None, Python is likely shutting down```

**Comment by luizoti** [comment]
How was Xkey chosen? Because he is not able to access the DISPLAY

**Comment by CSpencerND** [comment]
Interesting. I'm not sure what you mean by "chosen". I installed with `pip`. Made the config file, and ran it with `sudo xkeysnail ~/.config/xkeysnail/config.py`. 
I'm on a laptop with no extra display connected.

**Comment by luizoti** [comment]
I also don't know where the word 'chosen' came from. haha

I'm not talking about monitors, but about DISPLAY, maybe that explains it better: [display](https://askubuntu.com/questions/432255/what-is-the-display-environment-variable)

I had the same problem running xkeysnail through a systemd service.

**Comment by CSpencerND** [comment]
It's works after running `xhost +`.
Thanks very much.

**Comment by joshgoebel** [comment]
@gk2803 Did you get this working?

**Comment by gk2803** [comment]
> 

nope

**Comment by luizoti** [comment]
> > 
> 
> nope

This error?

```ImportError: sys.meta_path is None, Python is likely shutting down```
