### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by soype** [mooz/xkeysnail#165]
I'm on Manjaro and I installed xkeysnail via yay (yay -S xkeysnail).

The app seems to be installed as I can run it from the terminal but I always get this message which leads me to believe maybe my install didn't go as planned?

Running with sudo:

>Traceback (most recent call last):
  File "/usr/bin/xkeysnail", line 6, in <module>
    cli_main()
  File "/usr/lib/python3.10/site-packages/xkeysnail/__init__.py", line 62, in cli_main
    eval_file(args.config)
  File "/usr/lib/python3.10/site-packages/xkeysnail/__init__.py", line 5, in eval_file
    with open(path, "rb") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.config/xkeysnail/config.py'

Without sudo
>Traceback (most recent call last):
  File "/usr/bin/xkeysnail", line 6, in <module>
    cli_main()
  File "/usr/lib/python3.10/site-packages/xkeysnail/__init__.py", line 62, in cli_main
    eval_file(args.config)
  File "/usr/lib/python3.10/site-packages/xkeysnail/__init__.py", line 5, in eval_file
    with open(path, "rb") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/pedroh/.config/xkeysnail/config.py'

**Comment by joshgoebel** [comment]
You need a config file at that location named.

**Comment by soype** [comment]
The installer doesn't do that? I haven't seen anywhere in the instructions that I should create one

**Comment by joshgoebel** [comment]
No. Without a config file to tell us what to remap the software would do nothing at all. If you want something with an "out of the box" config maybe look at Kinto.sh?

**Comment by soype** [comment]
> No. Without a config file to tell us what to remap the software would do nothing at all. If you want something with an "out of the box" config maybe look at Kinto.sh?

Thanks. How do I create a working config.py? I've cd into the route and run sudo nano config.py to get a blank file but I still get this error when I run sudo xkeysnail 

usage: xkeysnail [-h] [--devices device [device ...]] [--watch] [-q] config.py
xkeysnail: error: the following arguments are required: config.py

**Comment by joshgoebel** [comment]
See me comment on the other thread.
