### ISSUE TITLE
error while running pyautogui in pycharm in linux

### ISSUE THREAD

**Issue by werewolf1011** [mooz/xkeysnail#170]
please help me solving this error i get while running pyautogui in pycharm in linux !!!

Traceback (most recent call last):
  File "/home/werewolf/PycharmProjects/pythonProject1/main.py", line 1, in <module>
    import pyautogui
  File "/usr/local/lib/python3.11/dist-packages/pyautogui/__init__.py", line 249, in <module>
    import mouseinfo
  File "/usr/local/lib/python3.11/dist-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/usr/local/lib/python3.11/dist-packages/Xlib/protocol/display.py", line 129, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":1": b'Authorization required, but no authorization protocol specified\n'

![Screenshot from 2023-01-26 15-00-22](https://user-images.githubusercontent.com/105560811/214850456-29dd5ed8-378c-42d0-a200-cf1ddd2de442.png)

**Comment by Razamindset** [comment]
I am getting the same issue did u find any fix

**Comment by Razamindset** [comment]
So i was able to solve the issue on ubuntu lts. When logging in go to the setting button at the bottom right and change the mode. I think it was something like xhr or so select it and log in this will solve the issue
