### ISSUE TITLE
OSError: could not open uinput device in write mode

### ISSUE THREAD

**Issue by mihaiolteanu** [mooz/xkeysnail#23]
```
> sudo xkeysnail config.py 

Traceback (most recent call last):
  File "/usr/bin/xkeysnail", line 6, in <module>
    cli_main()
  File "/usr/lib/python3.6/site-packages/xkeysnail/__init__.py", line 34, in cli_main
    if not has_access_to_uinput():
  File "/usr/lib/python3.6/site-packages/xkeysnail/__init__.py", line 11, in 
    has_access_to_uinput from xkeysnail.output import _uinput
  File "/usr/lib/python3.6/site-packages/xkeysnail/output.py", line 10, in <module>
    _uinput = UInput()
  File "/usr/lib/python3.6/site-packages/evdev/uinput.py", line 129, in __init__
    self.fd = _uinput.open(devnode)
OSError: could not open uinput device in write mode
```
Tested on ArchLinux.

Random rant: The sad thing is, I'm trying to replace xkeysnail and Firefox with cVim and Chromium, but Chromium is stubborn in keeping the shortcuts to himself.

**Comment by ymkjp** [comment]
For people trying to use xkeysnail with ArchLinux, install `evdev` as like below:

```
pacman -S xf86-input-evdev
```

Refer to [Xorg#Input_devices \- ArchWiki](https://wiki.archlinux.org/index.php?title=Xorg&oldid=564452#Input_devices) for more details.
