### ISSUE TITLE
NameError: name 'with_or_set_mark' is not defined

### ISSUE THREAD

**Issue by bradprob** [mooz/xkeysnail#30]
Hi,
executing the command: "sudo xkeysnail config.py" results in (default config.py):
Traceback (most recent call last):
File "/usr/bin/xkeysnail", line 6, in
cli_main()
File "/usr/lib/python3.4/site-packages/xkeysnail/init.py", line 44, in cli_main
eval_file(args.config)
File "/usr/lib/python3.4/site-packages/xkeysnail/init.py", line 5, in eval_file
exec(compile(file.read(), path, 'exec'), globals())
File "config.py", line 84, in
K("C-M-space"): with_or_set_mark(K("C-right")),
NameError: name 'with_or_set_mark' is not defined

**Comment by Lenbok** [comment]
I had this when I tried to use the example config downloaded from here on github here along with an older version of xkeysnail installed via pip (which is somewhat outdated). Either comment out that binding in your config or upgrade your xkeysnail from source.

**Comment by bradprob** [comment]
thanks!

**Comment by thapakazi** [comment]
stumbled into same thing.
*Would be nice if latest xkeysnail head be updated on pip src upstream.*

Wonder it is, fresh pip also installs the same version **(v0.1.0)** but is missing this method.

**Comment by mooz** [comment]
Sorry all. Will update the pip package soon.

**Comment by EskoJTH** [comment]
Pip does not seem to be updated yet. Needed to install from source.

**Comment by joshgoebel** [comment]
Is this still an issue?

**Comment by joshgoebel** [comment]
Ping.
