### ISSUE TITLE
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'No protocol specified\n'

### ISSUE THREAD

**Issue by kozo2** [mooz/xkeysnail#35]
## my env
- DELL XPS13 (9343)
- Ubuntu 18.04.1 LTS (Bionic Beaver) Desktop
- xkeysnail 0.1.0

## how to reproduce the error

```
kozo2@kozo2-XPS-13-9343:~/Downloads/xkeysnail-master/example$ which python3
/usr/bin/python3
kozo2@kozo2-XPS-13-9343:~/Downloads/xkeysnail-master/example$ python3 -V
Python 3.6.6
kozo2@kozo2-XPS-13-9343:~/Downloads/xkeysnail-master/example$ python3 -m pip -V
pip 18.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
kozo2@kozo2-XPS-13-9343:~/Downloads/xkeysnail-master/example$ python3 -m pip list
Package               Version  
--------------------- ---------
apturl                0.5.2    
asn1crypto            0.24.0   
Brlapi                0.6.6    
certifi               2018.1.18
chardet               3.0.4    
command-not-found     0.3      
cryptography          2.1.4    
cupshelpers           1.0      
defer                 1.0.6    
distro-info           0.18     
evdev                 1.1.2    
httplib2              0.9.2    
idna                  2.6      
keyring               10.6.0   
keyrings.alt          3.0      
language-selector     0.1      
launchpadlib          1.10.6   
lazr.restfulclient    0.13.5   
lazr.uri              1.0.3    
louis                 3.5.0    
macaroonbakery        1.1.3    
Mako                  1.0.7    
MarkupSafe            1.0      
oauth                 1.0.1    
olefile               0.45.1   
pexpect               4.2.1    
Pillow                5.1.0    
pip                   18.1     
protobuf              3.0.0    
pycairo               1.16.2   
pycrypto              2.6.1    
pycups                1.9.73   
pygobject             3.26.1   
pymacaroons           0.13.0   
PyNaCl                1.1.2    
pyRFC3339             1.0      
python-apt            1.6.3    
python-debian         0.1.32   
python-xlib           0.23     
pytz                  2018.3   
pyxdg                 0.25     
PyYAML                3.12     
reportlab             3.4.0    
requests              2.18.4   
requests-unixsocket   0.1.5    
SecretStorage         2.3.1    
setuptools            39.0.1   
simplejson            3.13.2   
six                   1.11.0   
system-service        0.3      
systemd-python        234      
ubuntu-drivers-common 0.0.0    
ufw                   0.35     
unattended-upgrades   0.1      
urllib3               1.22     
usb-creator           0.3.3    
wadllib               1.3.2    
wheel                 0.30.0   
xkeysnail             0.1.0    
xkit                  0.0.0    
zope.interface        4.3.2    
kozo2@kozo2-XPS-13-9343:~/Downloads/xkeysnail-master/example$ which xkeysnail
/usr/local/bin/xkeysnail
kozo2@kozo2-XPS-13-9343:~/Downloads/xkeysnail-master/example$ sudo xkeysnail config.py
[sudo] password for kozo2: 

██╗  ██╗██╗  ██╗███████╗██╗   ██╗
╚██╗██╔╝██║ ██╔╝██╔════╝╚██╗ ██╔╝
 ╚███╔╝ █████╔╝ █████╗   ╚████╔╝
 ██╔██╗ ██╔═██╗ ██╔══╝    ╚██╔╝
██╔╝ ██╗██║  ██╗███████╗   ██║
╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝   ╚═╝
  ███████╗███╗   ██╗ █████╗ ██╗██╗
  ██╔════╝████╗  ██║██╔══██╗██║██║
  ███████╗██╔██╗ ██║███████║██║██║
  ╚════██║██║╚██╗██║██╔══██║██║██║
  ███████║██║ ╚████║██║  ██║██║███████╗
  ╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝╚══════╝
                             v0.1.0

Traceback (most recent call last):
  File "/usr/local/bin/xkeysnail", line 6, in <module>
    cli_main()
  File "/usr/local/lib/python3.6/dist-packages/xkeysnail/__init__.py", line 44, in cli_main
    eval_file(args.config)
  File "/usr/local/lib/python3.6/dist-packages/xkeysnail/__init__.py", line 5, in eval_file
    exec(compile(file.read(), path, 'exec'), globals())
  File "config.py", line 4, in <module>
    from xkeysnail.transform import *
  File "/usr/local/lib/python3.6/dist-packages/xkeysnail/transform.py", line 13, in <module>
    def get_active_window_wm_class(display=Xlib.display.Display()):
  File "/usr/local/lib/python3.6/dist-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/local/lib/python3.6/dist-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/local/lib/python3.6/dist-packages/Xlib/protocol/display.py", line 167, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'No protocol specified\n'
kozo2@kozo2-XPS-13-9343:~/Downloads/xkeysnail-master/example$ cat config.py 
# -*- coding: utf-8 -*-

import re
from xkeysnail.transform import *

# [Global modemap] Change modifier keys as in xmodmap
define_modmap({
    Key.CAPSLOCK: Key.LEFT_CTRL
})

# [Conditional modmap] Change modifier keys in certain applications
define_conditional_modmap(re.compile(r'Emacs'), {
    Key.RIGHT_CTRL: Key.ESC,
})

# [Multipurpose modmap] Give a key two meanings. A normal key when pressed and
# released, and a modifier key when held down with another key. See Xcape,
# Carabiner and caps2esc for ideas and concept.
define_multipurpose_modmap(
    # Enter is enter when pressed and released. Control when held down.
    {Key.ENTER: [Key.ENTER, Key.RIGHT_CTRL]}

    # Capslock is escape when pressed and released. Control when held down.
    # {Key.CAPSLOCK: [Key.ESC, Key.LEFT_CTRL]
    # To use this example, you can't remap capslock with define_modmap.
)


# Keybindings for Firefox/Chrome
define_keymap(re.compile("Firefox|Google-chrome"), {
    # Ctrl+Alt+j/k to switch next/previous tab
    K("C-M-j"): K("C-TAB"),
    K("C-M-k"): K("C-Shift-TAB"),
    # Type C-j to focus to the content
    K("C-j"): K("C-f6"),
    # very naive "Edit in editor" feature (just an example)
    K("C-o"): [K("C-a"), K("C-c"), launch(["gedit"]), sleep(0.5), K("C-v")]
}, "Firefox and Chrome")
kozo2@kozo2-XPS-13-9343:~/Downloads/xkeysnail-master/example$ 

```

**Comment by kozo2** [comment]
I don't know why but xkeysnail worked well after the following commands.

```
kozo2@kozo2-XPS-13-9343:~/Downloads/xkeysnail-master/example$ xhost +
access control disabled, clients can connect from any host
kozo2@kozo2-XPS-13-9343:~/Downloads/xkeysnail-master/example$ sudo xhost +
[sudo] password for kozo2: 
access control disabled, clients can connect from any host
kozo2@kozo2-XPS-13-9343:~/Downloads/xkeysnail-master/example$ sudo xkeysnail config.py 

██╗  ██╗██╗  ██╗███████╗██╗   ██╗
╚██╗██╔╝██║ ██╔╝██╔════╝╚██╗ ██╔╝
 ╚███╔╝ █████╔╝ █████╗   ╚████╔╝
 ██╔██╗ ██╔═██╗ ██╔══╝    ╚██╔╝
██╔╝ ██╗██║  ██╗███████╗   ██║
╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝   ╚═╝
  ███████╗███╗   ██╗ █████╗ ██╗██╗
  ██╔════╝████╗  ██║██╔══██╗██║██║
  ███████╗██╔██╗ ██║███████║██║██║
  ╚════██║██║╚██╗██║██╔══██║██║██║
  ███████║██║ ╚████║██║  ██║██║███████╗
  ╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝╚══════╝
                             v0.1.0

No keyboard devices specified via (--devices) option.
xkeysnail picks up keyboard-ish devices from the list below:

----------------------------------------------------------------------------------
Device               Name                                Phys
----------------------------------------------------------------------------------
/dev/input/event0    Lid Switch                          PNP0C0D/button/input0
/dev/input/event1    Power Button                        PNP0C0C/button/input0
/dev/input/event2    Sleep Button                        PNP0C0E/button/input0
/dev/input/event3    Power Button                        LNXPWRBN/button/input0
/dev/input/event4    AT Translated Set 2 keyboard        isa0060/serio0/input0
/dev/input/event5    Video Bus                           LNXVIDEO/video/input0
/dev/input/event6    Integrated_Webcam_HD: Integrate     usb-0000:00:14.0-5/button
/dev/input/event7    Dell WMI hotkeys                    
/dev/input/event8    DLL0665:01 06CB:76AD Touchpad       i2c-DLL0665:01
/dev/input/event9    HDA Intel PCH Headphone Mic         ALSA
/dev/input/event10   HDA Intel HDMI HDMI/DP,pcm=3        ALSA
/dev/input/event11   HDA Intel HDMI HDMI/DP,pcm=7        ALSA
/dev/input/event12   HDA Intel HDMI HDMI/DP,pcm=8        ALSA
/dev/input/event13   HDA Intel HDMI HDMI/DP,pcm=9        ALSA
/dev/input/event14   HDA Intel HDMI HDMI/DP,pcm=10       ALSA
/dev/input/event15   py-evdev-uinput                     py-evdev-uinput

Okay, now enable remapping on the following device(s):

------------------------------------------------------------------------------
Device               Name                                Phys
------------------------------------------------------------------------------
/dev/input/event4    AT Translated Set 2 keyboard        isa0060/serio0/input0

WM_CLASS 'Gnome-terminal' | active keymaps = []
C-Shift-C


```

**Comment by Lenbok** [comment]
This is not a bug, and is already described in the Usage section of README.md

**Comment by kozo2** [comment]
@Lenbok 
Thank you for the information.
Now I found https://github.com/mooz/xkeysnail/commit/9f3a79ab77eea6c581414bbbcc3b90db5eff5c26
I close this issue. (sorry @mooz )
