### ISSUE TITLE
Is not my function supported ?

### ISSUE THREAD

**Issue by aiya000** [mooz/xkeysnail#8]
Hi, thank you for this great product!

I have a problem, I made below `config.py` as `xkeysnail.py`

```python
import re
from xkeysnail.transform import *

def char_to_string_of_a_stroke(x):
    return 'Shift-' + x.lower() if x.isupper() else x

def strokes(key_chars):
    xs = list(key_chars)
    xs = map(char_to_string_of_a_stroke, xs)
    xs = map(K, xs)
    return list(xs)

define_keymap(re.compile('Vivaldi-stable'), {
    K('C-n'): strokes('gt'),
    K('C-p'): strokes('gT'),
}, 'vivaldi')
```

and got

```console
$ >>> sudo xkeysnail xkeysnail.py --devices /dev/input/event14

██╗  ██╗██╗  ██╗███████╗██╗   ██╗
╚██╗██╔╝██║ ██╔╝██╔════╝╚██╗ ██╔╝
 ╚███╔╝ █████╔╝ █████╗   ╚████╔╝
 ██╔██╗ ██╔═██╗ ██╔══╝    ╚██╔╝
██╔╝ ██╗██║  ██╗███████╗   ██║
╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝   ╚═╝
  ███████╗███╗   ██╗ █████╗ ██╗██╗
  ██╔════╝████╗  ██║██╔══██╗██║██║
  ███████╗██╔██╗ ██║███████║██║██║
  ╚════██║██║╚██╗██║██╔══██║██║██║
  ███████║██║ ╚████║██║  ██║██║███████╗
  ╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝╚══════╝
                             v0.0.9

Traceback (most recent call last):
  File "/bin/xkeysnail", line 6, in <module>
    cli_main()
  File "/usr/lib/python3.6/site-packages/xkeysnail/__init__.py", line 44, in cli_main
    eval_file(args.config)
  File "/usr/lib/python3.6/site-packages/xkeysnail/__init__.py", line 5, in eval_file
    exec(compile(file.read(), path, 'exec'))
  File "xkeysnail.py", line 16, in <module>
    K('C-n'): strokes('gt'),
  File "xkeysnail.py", line 11, in strokes
    xs = map(char_to_string_of_a_stroke, xs)
NameError: name 'char_to_string_of_a_stroke' is not defined
```

Is my `strokes` function supported ?

**Comment by mooz** [comment]
Thanks for the report. Looks like the issue is caused by scope-related issue in the current configuration evaluation mechanism. I will work on the issue later.

**Comment by aiya000** [comment]
👍
