### ISSUE TITLE
Can not set up xkeysnail, looking for help

### ISSUE THREAD

**Issue by samrayleung** [mooz/xkeysnail#9]
Hey, Mr. mooz, I install `xkeysnail` as what README guides, but I still could not set it up. There is an error I try `sudo xkeysnail examples/config.py`:
```
Traceback (most recent call last):
  File "/usr/local/bin/xkeysnail", line 6, in <module>
    cli_main()
  File "/usr/local/lib/python3.6/site-packages/xkeysnail/__init__.py", line 44, in cli_main
    eval_file(args.config)
  File "/usr/local/lib/python3.6/site-packages/xkeysnail/__init__.py", line 5, in eval_file
    exec(compile(file.read(), path, 'exec'), globals())
  File "config.py", line 4, in <module>
    from xkeysnail.transform import *
  File "/usr/local/lib/python3.6/site-packages/xkeysnail/transform.py", line 13, in <module>
    def get_active_window_wm_class(display=Xlib.display.Display()):
  File "/usr/local/lib/python3.6/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/local/lib/python3.6/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/local/lib/python3.6/site-packages/Xlib/protocol/display.py", line 167, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0.0": b'No protocol specified\n'
```  
Information about my OS:
+ fedora 27
+ XFCE environment 
+ python2.7 and python3.6 installed 
-----
Is there something wrong with my environment ?

**Comment by mooz** [comment]
Though I cannot reproduce the issue in my environment, several guys report that we may need to explicitly allow root users to connect to X server.

Could you try the following procedure?

    xhost +SI:localuser:root
    sudo xkeysnail examples/config.py

See https://aur.archlinux.org/packages/kwplayer/ and https://qiita.com/miy4/items/dd0e2aec388138f803c5 (in Japanese) for details.

**Comment by mooz** [comment]
Yes. It means so.

**Comment by samrayleung** [comment]
Thanks so much for your help :)
